version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - node_modules:/app/node_modules
    networks:
      - mynetwork

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    ports:
      - "1339:1339"
    networks:
      - mynetwork

  production:
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
      target: production
    ports:
      - "8080:1339"
    networks:
      - mynetwork
    env_file:
      - ./backend/.env

  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "5"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
      - ./dhparam/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

networks:
  mynetwork:
    driver: bridge
volumes:
  node_modules: {}
