version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5174:5174"
    depends_on:
      - backend
    volumes:
    - node_modules:/app/node_modules
    networks:
    - mynetwork

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "1339:1339"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
volumes:
  node_modules: {}